# This is a generated file. Not intended for manual editing.
services:
  frontend:
    build:
      context: "C:\\ES2\\TP_ES2"
      dockerfile: "Frontend/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Frontend.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Frontend.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "frontend:dev"
    ports: []
    volumes:
    - "C:\\Users\\alexp\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\ES2\\TP_ES2\\Frontend:/app:rw"
    - "C:\\ES2\\TP_ES2:/src:rw"
    working_dir: "/app"
  webapi:
    build:
      context: "C:\\ES2\\TP_ES2"
      dockerfile: "WebAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ESOF WebApp WebAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\alexp\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\ES2\\TP_ES2\\WebAPI:/app:rw"
    - "C:\\ES2\\TP_ES2:/src:rw"
    working_dir: "/app"
